AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false
