# Contains all requires for Database Gauge applicaion.
require 'gauge/console_listener'
require 'gauge/database_inspector'
require 'gauge/helper'
require 'gauge/repo'
require 'gauge/schema/database_schema'
require 'gauge/schema/data_table_schema'
require 'gauge/shell'
require 'gauge/validators/database_validator'
require 'gauge/validators/table_validator'
require 'gauge/version'

require 'gli'
require 'rainbow'
require 'rainbow/ext/string'
