# Eithery, 2020
# Gauge app configuration options
---
# Server name
server: localhost

# User DB credentials
user: admin
password: secret

# Determines whether console output is colored
colored: true

# The array of paths with Gauge metadata
# Can be relative or absolute
data_path: [db]
